-- Two key-generation fixes. Neither rewrites a table.

-- 1. bigserial -> GENERATED BY DEFAULT AS IDENTITY.
--    A bigint surrogate is the right choice for this table (append-only, high
--    volume, referenced by chat_attachments.message_id bigint) and it should not
--    become a uuid. What is worth fixing is serial itself: it permits an explicit
--    insert that desynchronizes the sequence, and its sequence ownership makes
--    later ALTER TABLE interactions messier. BY DEFAULT rather than ALWAYS, since
--    a future backfill may want to supply ids even though nothing does today.
DO $$
DECLARE
    next_id bigint;
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'chat_dialog_messages'::regclass
          AND attname = 'id' AND attidentity = ''
    ) THEN
        SELECT COALESCE(max(id), 0) + 1 INTO next_id FROM chat_dialog_messages;

        ALTER TABLE chat_dialog_messages ALTER COLUMN id DROP DEFAULT;
        DROP SEQUENCE IF EXISTS chat_dialog_messages_id_seq;
        EXECUTE format(
            'ALTER TABLE chat_dialog_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
            next_id);
    END IF;
END
$$;

-- 2. uuidv7() for the append-heavy uuid keys.
--    gen_random_uuid() is v4, so every insert lands at a random point in the
--    B-tree. uuidv7() is time-ordered and gives far better index locality. New
--    rows only; existing ids are untouched and both are valid uuids.
--
--    Guarded, because uuidv7() is PostgreSQL 18 and externalDatabase lets an
--    operator point nib at an older server. On anything older this is a no-op
--    and gen_random_uuid() stays.
--
--    chat_attachments is deliberately left out: its id is generated in Go before
--    the file is written, so the column default is never reached.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'uuidv7' AND pronargs = 0) THEN
        ALTER TABLE chat_dialogs ALTER COLUMN id SET DEFAULT uuidv7();
        ALTER TABLE kb_chunks    ALTER COLUMN id SET DEFAULT uuidv7();
    ELSE
        RAISE NOTICE 'uuidv7() not available, keeping gen_random_uuid() defaults';
    END IF;
END
$$;
